# Nginx
nginx:
  build: ./Nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    # app
    - /Users/leepin/Documents/Developer/App/Web:/app
    - /Users/leepin/Documents/Developer/App/nginx/nginx.conf:/opt/nginx/conf/nginx.conf
    - /Users/leepin/Documents/Developer/App/nginx/vhost:/opt/nginx/conf/vhost
    - /Users/leepin/Documents/Developer/App/nginx/logs:/opt/nginx/logs
  links:
    - php

# PHP
php:
  build: ./PHP
  ports:
    - "9000"
  volumes:
    - /Users/leepin/Documents/Developer/App/php/php-fpm.conf:/opt/php/etc/php-fpm.conf
    - /Users/leepin/Documents/Developer/App/php/www.conf:/opt/php/etc/php-fpm.d/www.conf
    - /Users/leepin/Documents/Developer/App/php/php.ini:/opt/php/etc/php.ini
    - /Users/leepin/Documents/Developer/App/php/logs:/opt/logs
    - /Users/leepin/Documents/Developer/App/web:/app
  links:
    - mysql
    - redis

# MySQL
mysql:
  image: daocloud.io/mysql:5.7
  ports:
    - "3306:3306"
  volumes:
    - /Users/leepin/Documents/Developer/App/mysql/database:/var/lib/mysql
    - /Users/leepin/Documents/Developer/App/mysql/my.cnf:/etc/my.cnf
  environment:
    MYSQL_ROOT_PASSWORD: 1008611

# REDIS
redis:
  build: ./Redis
  ports:
    - "6379:6379"
  volumes:
    - /Users/leepin/Documents/Developer/App/redis:/app
