# Nginx
nginx:
  build: ./Nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    # app
    - ./App/Web:/app
    - ./App/nginx/nginx.conf:/opt/nginx/conf/nginx.conf
    - ./App/nginx/vhost:/opt/nginx/conf/vhost
    - ./App/nginx/logs:/opt/nginx/logs
  links:
    - php

# PHP
php:
  build: ./PHP
  ports:
    - "9000"
  volumes:
    - ./App/php/php-fpm.conf:/opt/php/etc/php-fpm.conf
    - ./App/php/www.conf:/opt/php/etc/php-fpm.d/www.conf
    - ./App/php/php.ini:/opt/php/etc/php.ini
    - ./App/php/logs:/opt/logs
    - ./App/web:/app
  links:
    - mysql
    - redis
    - beanstalkd
    - memcached

# MySQL
mysql:
  image: daocloud.io/mysql:5.7
  ports:
    - "127.0.0.1:3306:3306"
  volumes:
    - ./App/mysql/database:/var/lib/mysql
    - ./App/mysql/my.cnf:/etc/my.cnf
  environment:
    MYSQL_ROOT_PASSWORD: 1008611

# REDIS
redis:
  build: ./Redis
  ports:
    - "127.0.0.1:6379:6379"
  volumes:
    - ./App/redis:/app

# Memcached
memcached:
  build: ./Memcached
  ports:
    - "127.0.0.1:11211:11211"

# Beanstalkd
beanstalkd:
  build: ./Beanstalkd
  ports:
    - "127.0.0.1:11300:11300"
  volumes:
    - ./App/beanstalkd:/app

