# Nginx
nginx:
  build: ./Nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    # app
    - ./app/web:/app
    - ./app/nginx/nginx.conf:/opt/nginx/conf/nginx.conf
    - ./app/nginx/vhost:/opt/nginx/conf/vhost
  links:
    - php

# PHP
php:
  build: ./PHP
  ports:
    - "9000"
  volumes:
    - ./app/php/php-fpm.conf:/opt/php/etc/php-fpm.conf
    - ./app/php/www.conf:/opt/php/etc/php-fpm.d/www.conf
    - ./app/php/php.ini:/opt/php/etc/php.ini
    - ./app/php/logs:/opt/logs
    - ./app/web:/app
  links:
    - mysql
    - redis

# MariaDB
mysql:
  image: daocloud.io/mysql:5.7
  ports:
    - "3306:3306"
  volumes:
    - ./app/mysql/database:/var/lib/mysql
    - ./app/mysql/my.cnf:/etc/my.cnf
  environment:
    - MYSQL_ROOT_PASSWORD=1008611

# REDIS
redis:
  build: ./Redis
  ports:
    - "6379:6379"
  volumes:
    - ./app/redis:/app
